name: CI

on:
  pull_request:

jobs:
  Build-and-Push-Image:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and Push Image to Image registry
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      ORGANIZATION_NAME: kahootali
      TOKEN: ${{ secrets.TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      REGISTRY: docker.io
      DOCKERHUB_USER: '${{ secrets.DOCKERHUB_USER }}'
      DOCKERHUB_PASSWORD: '${{ secrets.DOCKERHUB_PASSWORD }}'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Initialize Pipeline
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_WORKFLOW_URL: https://github.com/${ORGANIZATION_NAME}/${REPO_NAME}/actions/runs/$GITHUB_RUN_ID
        with:
          message: '@${{ github.actor }} GitHub Actions has started building this code. Check status at ${{ env.GITHUB_WORKFLOW_URL }}'
          allow-repeats: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: |
            $IMAGE
          labels: |
            Developer: "Ali Kahoot"
      - name: Comment on PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '@${{ github.actor }} Image is available for testing. `docker pull ${{ github.repository }}:${{ steps.generate_tag.outputs.GIT_TAG }}`'
          allow-repeats: false

      - name: Notify Failure
        if: failure()
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: '@${{ github.actor }} The pipeline failed! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
          allow-repeats: false